/**
 * Echo Protocol Smart Contract ABIs (auto-generated from compiled contracts)
 * 
 * To generate:
 *   cd packages/contracts
 *   forge build
 *   cat out/MarketRegistry.sol/MarketRegistry.json | jq '.abi' > ../sdk/src/abis/MarketRegistry.json
 * 
 * Then copy / import the JSON here.
 */

// Placeholder — real ABIs generated by forge build
export const MarketRegistryABI = [] as const;
export const EchoHookABI = [] as const;
export const ParticipationReceiptABI = [] as const;
